### ISSUE TITLE
FeatReq: allow base_url to be changed

### ISSUE THREAD

**Issue by petiepooo** [target/strelka-ui#46]
Would it be possible to allow the base URL to be changed?  Eg: instead of the main page being available at /, have that redirect to /strelkaui/ or something else, and the main page plus api and other resources) be available under /strelkaui/.

I see the api url can be updated, but not the main page and the components it loads.

I find it's often easier to reverse-proxy an app under a sub-url when the app itself is generating its hrefs with that sub-url already.  That way the app can easily share the same proxy url with other apps, each using a different sub-url, and no rewriting the response contents is required.

**Comment by phutelmyer** [comment]
I'll see what I can do, put together a PR, and see if it's what you're looking for @petiepooo.

**Comment by phutelmyer** [comment]
@petiepooo - Any thoughts? Otherwise I'll clean it up early next week or so, get it tested, and rolled out.

https://github.com/target/strelka-ui/pull/47

**Comment by petiepooo** [comment]
That's exactly what i was looking for.  Thank you!

**Comment by phutelmyer** [comment]
Should be implemented in #47 - will generate a release shortly.

**Comment by petiepooo** [comment]
@phutelmyer getting around to testing this locally, and I can't figure out how to get this to take effect.  A setting in .env?  What should it look like?
